// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NuhG0QswzgvEXowq7054ItOnnMVu8cQ',
    appId: '1:429922846076:web:de2eee8a43590bba89d0f9',
    messagingSenderId: '429922846076',
    projectId: 'mychatapp-781b9',
    authDomain: 'mychatapp-781b9.firebaseapp.com',
    storageBucket: 'mychatapp-781b9.appspot.com',
    measurementId: 'G-7NBYGJJMPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD18IIMs8O73VCZL7t9O-0o3_XEmWxr9gU',
    appId: '1:429922846076:android:015441300e2f43e189d0f9',
    messagingSenderId: '429922846076',
    projectId: 'mychatapp-781b9',
    storageBucket: 'mychatapp-781b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsExsLQDaUkasyOSAjtWJ2tt_cQyFeWs',
    appId: '1:429922846076:ios:24d80a7c7b29da7a89d0f9',
    messagingSenderId: '429922846076',
    projectId: 'mychatapp-781b9',
    storageBucket: 'mychatapp-781b9.appspot.com',
    iosClientId: '429922846076-5dqu3enhrlbdn4bau5bn5ea2un35js0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnsExsLQDaUkasyOSAjtWJ2tt_cQyFeWs',
    appId: '1:429922846076:ios:24d80a7c7b29da7a89d0f9',
    messagingSenderId: '429922846076',
    projectId: 'mychatapp-781b9',
    storageBucket: 'mychatapp-781b9.appspot.com',
    iosClientId: '429922846076-5dqu3enhrlbdn4bau5bn5ea2un35js0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
